export const FETCH_PRODUCT_LOADING = 'FETCH_PRODUCT_LOADING';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';

export const TOGGLE_STYLE_FILTER = 'TOGGLE_STYLE_FILTER';
export const SHOW_FILTER_STYLE_BOX = 'SHOW_FILTER_STYLE_BOX';
export const CHANGE_KEYWORDS = 'CHANGE_KEYWORDS';
export const CHANGE_DELIVERY_TIME = 'CHANGE_DELIVERY_TIME';